### ISSUE TITLE
openav-manual translations

### ISSUE THREAD

**Issue by trebmuh** [openAVproductions/openAV-manual#33]
Hi @harryhaaren , I hope everything is fine for you.

I'm wondering what is the current status of the online non-EN manual translations.

I'm pretty sure that you're overbooked, still I feel a bit sadish that the FR-manual isn't online in regard with the time sub26nico and I spent on doing the translation. I know I can still access it but a few weeks ago you asked on IRC not to spread out the trick. I also know that a bunch of French readers not comfortable with reading English would appreciate a lot this online manual for the great openavproduction software.

I hope I'm not too much of a PITA here, I'm just checking how things are going :)

**Edit:** I forgot to add the usual "_if I can be of any help within my ropes, please let me know_".

**Comment by harryhaaren** [comment]
Hi @trebmuh ; thanks for the ping. Indeed it has taken me too long to get the manual back online - and I apologize for that. Please have a look now, and see are all the links working correctly!

A "manual" page has been added to the menu - please have a look - suggestions welcome:
http://openavproductions.com/manual/

Thanks for reminding me to fix this, -Harry

**Comment by trebmuh** [comment]
Awesome. Thanks for putting it back online. It's very appreciated 👍 

I've had a quick look at it and it looks pretty fine. I'll try to have a look at every page of the FR translations on the coming days and will let you know if I find something which needs to be fixed.

Something I can think of right now would be to put the names of the translators on the related pages (such as : the names of the French translators on the French main page, the names of the German translators on the German main page,...).

@harryhaaren thanks again, really appreciated!

~~**Edit:** I just saw something which is looking like a typo in the http://openavproductions.com/manual/ page:  "...feel free to **file** pull-requests!..." -> "...feel free to **fill** pull-requests!..." (unless this is a pun).~~

**Edit 2:** another typo on the same page, the link name: "English (primary langauge)" -> "English (primary language)".

**Comment by coderkun** [comment]
> Edit: I just saw something which is looking like a typo in the http://openavproductions.com/manual/ page: "...feel free to file pull-requests!..." -> "...feel free to fill pull-requests!..." (unless this is a pun).

@trebmuh, you do not “fill” PRs, you “file” them. “create” or “submit” would work, too, I guess.

**Comment by trebmuh** [comment]
Oh really ? I could have swear it was "filling a pull request" like "[filling something with](http://dictionary.cambridge.org/dictionary/english/fill-someone-something-with-something)".

**Comment by coderkun** [comment]
(to) file (verb) from http://dictionary.cambridge.org/dictionary/english/file

> to store information in a careful and particular way:
> We file these reports […]

**Comment by trebmuh** [comment]
Good to know. Thanks.

**Comment by harryhaaren** [comment]
Fixed "language" typo, and used submit instead of file. I think that means this issue can be closed?

**Comment by trebmuh** [comment]
It is @harryhaaren . Thanks again for that.
